import type { Metadata } from "next";
import SessionWrapper from "@/components/SessionWrapper";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <SessionWrapper>
        <Navbar />
        {children}
      </SessionWrapper>
      ;
    </div>
  );
}
